<?php 

/**
 *ddsmanner.in ,www.ddsmanner.in
 * DDS MANNER Higher Secondary School
 * @link http://ddsmanner.in/
 * Built By: www.ddsmanner.in
 * Project Manager: Best School In Chiraiyakot, Mau
 * About School DDS Manner 
 *
 */

$this->load->view("header");?>

<div class="gray-line"></div>

<div class="page-header pattern-bg">
	<div class="container">
    	<div class="row">
        	<div class="span6">
            	<h2>About School</h2>
            </div>
            <div class="span6 trial">
				<style>
				.trial a:link {color:#fff;}
				.trial a:hover {color:#9EC64D;}
				</style>
            	<p><span style="color:#fff;"><a href='<?php echo base_url();?>index.php/welcome/index'>Home</a> / <a href='#'>About Us</a> / <a href='<?php echo base_url();?>index.php/welcome/ourvision'>Our Vision</a>  </span></p>
            </div>
        </div>
    </div>
</div>
<!-- header end //-->

<style>
.main-content-block{
	margin-top:0px;
}
</style>
<style>
.data-table table tr:nth-child(odd) {background-color:#eeeeee;}
.data-table table tr:nth-child(even) {background-color:#e4e4e4;}
.data-table table td {padding-left:10px;}

.data-table ul li {
	list-style-image: url('images/check.png');
	margin-left:30px;
	line-height:20px;
	margin-bottom:10px;
	margin-right: 35px;
}

.button-new {
	background-color: #95c23d;
	color:#fff;
	line-height: 24px;
	padding:10px 20px;
	margin: 1px;
	margin-left: 20px;
	overflow: hidden;
	display: block;
</style>
			
<!--main content start //-->
<div class="main-content" style="background: #fff;min-height:400px;">
    <div class="container" style="margin-top:40px;margin-bottom:40px;">
        <div class="row">
			<!-- Page Content start //-->
			<div class="span12">			
				 <p><img src="<?php echo base_url();?>assets/images/about.jpg" alt="" /></p>
<p style="text-align: justify;">WELCOME TO D.D.S. Manner Higher Secondary School.
The Manner School was established on 12 February in 1997. Since 1997 it has been functioning under the able guidance of Baba Pashupati das and Dr. Hriday Narayan Singh who has been involved in the field of education for the past Twenty years. The Manner School was upgraded to higher secondary level in 2014 with New name D.D.S. Manner Higher Secondary School in Dynamic directorship of Dr. Anand Narayan Singh Associate Professor & Head Department of Biochemistry G.S.V.M. Medical College Kanpur. </p>
<p style="text-align: justify;">At D.D.S. Manner we follow learning by doing. It has created a trust among school, children and parents. Further it created a strong bond among these three which is on the base of faith.</P><p style="text-align: justify;">
Our academic program has been designed in such a way that fulfills changing needs of time. We use modern teaching method. Our learning program is not based only books as well as it are based on assignment sheets, projects which could generate creativity in young buds. We give proper focus on “WHAT TO TEACH” as well as “HOW TO TEACH.”
As a seed has enormous possibility to become a big tree, provide fruits, shelter to common people. But in the absence of favorable environment seed cannot attain growth and development in the same way small kids/young buds/learners have enormous possibility of becoming a scholar, an administrator, a politician above all good citizen but these all cannot happen in the absence of a good environment </p>
<p style="text-align: justify;">D.D.S. Manner provides a peaceful harmonious environment to the children and the environment encourages Child’s development generates interest for learning and for teachers it insists to teach with full devotion and dedication. Teachers at D.D.S. Manner are like parents. They play attention towards every need of the students.</p>
<p style="text-align: justify;">The curriculum which is followed by D.D.S. Manner Higher Secondary School is contemporary, relevant to present day system. It provides complete package of knowledge, good habits, manners and inclined towards overall development of children. Curriculum has been designed in such a manner that children could explore their imagination, thoughtful and innovative ideas. School tries to make learning more innovative teaching method.
Keeping in mind Indian cultures and traditions we celebrate all the festivals with great sprit. Students are taught to love and respect one another. The school plays a great role in inculeating moral values through inspiring stories.</p>
<p style="text-align: justify;">Our school infrastructure includes two stories building in which classrooms are of standard size and airy, well maintained furniture, podium and other facilities create an effect and differentiate from others. School infrastructure consists of other facilities and amenities like Library, First Aid, Computer Lab, Science Lab, etc. These all facilities have been generated by school management according to contemporary demand of time and for better education. Schools provide facility of sport and create opportunity before students so that they could prepare themselves for carrier in this field.</p>
</p> 		
			</div>
        </div>
    </div>    
</div>
<!--main content end //-->
<?php $this->load->view("footer");?>